version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - serverPort=8080
      - devToken=${devToken}
      - secretJWT=${secretJWT}
    volumes:
      - .:/app
      - /app/node_modules
    command: node index.js
